### PR TITLE
TRITON-2118 kbmapi tests fail on modern postgres due to root restrictions

### PR DESCRIPTION
**Pull request by timfoster**

### CODE REVIEW

**Comment by timfoster** [comment]
Thanks for the review - would you be able to publish this to npm so that we can use this version in triton-kbmapi, for the other part of TRITON-2118?

**Comment by timfoster** [comment]
Sorry, to clarify - that's part of TOOLS-2461, so we can have the 2019Q4 bump of triton-kbmapi use this new node-moray-sandbox release.

**Comment by kusor** [comment]
Published:

```
dist-tags:
latest: 0.2.2

published just now by kusor <kusorbox@gmail.com>

```

**Comment by timfoster** [comment]
Thanks!

**Pull request merged**
